### ISSUE TITLE
Missing menu button

### ISSUE THREAD

**Issue by HedvigS** [aikuma/aikuma#533]
Sorry, this might be me just missing something: but I'm not getting a menu in the version of Aikuma that I downloaded to my new android phone.

https://drive.google.com/file/d/0B-lVFHmduY1WOENYSEdSbDZXbGc/view?usp=sharing

I downloaded both Aikuma and Aikuma2, neither of them have a menu button.. 

I feel a bit stupid, what am I missing?

**Comment by Lingomat** [comment]
It's not just you. You can use Android's menu button, probably a soft button on the bottom of your phone. This should be resolved though. Inclined to tag this as a bug unless anyone believes otherwise?

**Comment by HedvigS** [comment]
Aha!!! Thanks. I knew it was something simple like that. Sorry, just switched to Android fully.

**Comment by HedvigS** [comment]
(Next issue, why are my old recordings not showing up... perhaps I should poked around a bit more before and if I still don't get it start a new thread.)

**Comment by Lingomat** [comment]
Just to be clear, there should be a button at the top to access settings. The Android soft button at the bottom is not there all of the time, it might be re-purposed to be something else. Only the home/switch and back buttons are always there. 

I'd suggest posting questions like why things aren't working on the Android mailing list instead maybe? This was the right place for this settings menu button issue though, I reckon.

**Comment by HedvigS** [comment]
Ok, thanks.

**Comment by Lingomat** [comment]
Wait, I meant the Aikuma mailing list d'oh!

**Comment by stevenbird** [comment]
@HedvigS did you upgrade to the Google Play version of Aikuma 2 (which should pull in old recordings) or the development version available at aikuma.org (which does not pull in old recordings, yet at least).

**Comment by HedvigS** [comment]
The Google Play version.

**Comment by stevenbird** [comment]
OK, not sure why you wouldn't be seeing your old recordings, unless they were made with a really old version of Aikuma. I wonder if you've gone from using the development version, downloaded on the day of the ANU workshop, to using the Google Play version. That would account for not seeing the old recordings.

**Comment by HedvigS** [comment]
That's true, at the workshop at ANU I downloaded the developer version! That explains it.
